### ISSUE TITLE
Please consider Node-RED naming guidelines

### ISSUE THREAD

**Issue by knolleary** [muka/node-red-openfaas#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by muka** [comment]
Hi @knolleary no problem, is renaming on npm enough or also the repo?

**Comment by knolleary** [comment]
Thanks @muka. It's mainly the name on npm as that's what users see in the node catalog.

**Comment by muka** [comment]
Ok, done  

https://www.npmjs.com/package/node-red-contrib-openfaas

I also deprecated the previous one and will drop it in a few days

Please reopen if you have any concern or suggestion, thanks!

**Comment by knolleary** [comment]
Thank you!
