### ISSUE TITLE
node is broken on nodered v0.17.5 and Node.js v4.8.0

### ISSUE THREAD

**Issue by juzam** [muka/node-red-openfaas#2]
Tested on:
nodered v0.17.5
Node.js v4.8.0

Steps to reproduce:

- install node-red-contrib-openfaas via palette management 
- check nodered logs, the install is ok but gives a warning:
``[warn] [openfaas] SyntaxError: Unexpected token {``
- import the demo flow
- deploy and the flows are stopped because `openfaas` node type is not yet registered.

It might be something related to the version of Node.js used but I needed that in my Docker image because of another node incompatibility with Node.js v6.x

**Comment by muka** [comment]
Hi @juzam, need to check maybe there is some incompatible syntax with that version

**Comment by muka** [comment]
And if you want to provide a PR is really welcome! Thanks

**Comment by muka** [comment]
And if you want to provide a PR is really welcome! Thanks

**Comment by juzam** [comment]
@muka I'll see what I can do, I'm no js expert unfortunately. I can set up a test environment with Docker to compare different versions of Node.js (the official docker image is based on Node.js v6) 
what version of node did/do you use to run nodered?

**Comment by muka** [comment]
Hi, I can also give a look just let me a few days. I am using the latest
avail, 8.x I think

sent from my phone

Il 22 nov 2017 11:14 AM, "Giovanni Angoli" <notifications@github.com> ha
scritto:

**Comment by juzam** [comment]
a little update. the node installs and works just fine on nodejs 6.x

**Comment by muka** [comment]
Hi there, sorry had not chance to review at the end.. The node uses some features of ES6 I guess node 4.x was not supporting.

If you are interested in supporting 4.x series please provide a PR and I will be happy to review and merge, thanks

**Comment by juzam** [comment]
fair enough. since the default base image is 6.x and the raspberry pi script to update node-red/nodejs installs by default 6.x I think 6.x as a minimum supported version is OK. If I ever get a workable PR for 4.x I'll submit it, but this will be on a best effort model :)
